// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmgNzT3dJrQLgvyOuxczy05U3NLoKoiws',
    appId: '1:926323354090:web:e2957aa3befbf53f48ea93',
    messagingSenderId: '926323354090',
    projectId: 'soilmate-3735c',
    authDomain: 'soilmate-3735c.firebaseapp.com',
    storageBucket: 'soilmate-3735c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPORi79W9spENGA3mKw1O0D79E6YWEJS4',
    appId: '1:926323354090:android:b156cc4aa8f58bf848ea93',
    messagingSenderId: '926323354090',
    projectId: 'soilmate-3735c',
    storageBucket: 'soilmate-3735c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhFnT7VQgF59GBAo6SS0r5PSQI6NkCTrs',
    appId: '1:926323354090:ios:27dc113049fb5b7c48ea93',
    messagingSenderId: '926323354090',
    projectId: 'soilmate-3735c',
    storageBucket: 'soilmate-3735c.firebasestorage.app',
    iosBundleId: 'com.example.soilKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhFnT7VQgF59GBAo6SS0r5PSQI6NkCTrs',
    appId: '1:926323354090:ios:27dc113049fb5b7c48ea93',
    messagingSenderId: '926323354090',
    projectId: 'soilmate-3735c',
    storageBucket: 'soilmate-3735c.firebasestorage.app',
    iosBundleId: 'com.example.soilKit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmgNzT3dJrQLgvyOuxczy05U3NLoKoiws',
    appId: '1:926323354090:web:2ce54d43b818e4fb48ea93',
    messagingSenderId: '926323354090',
    projectId: 'soilmate-3735c',
    authDomain: 'soilmate-3735c.firebaseapp.com',
    storageBucket: 'soilmate-3735c.firebasestorage.app',
  );
}
